spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security-demo?useUnicode=yes&characterEncoding=utf-8
    username: root
    password: root
  session:
    store-type: redis
#  redis:
#    host:
#    port:

security:
  basic:
  # 打开/关闭spring security 打开默认的用户名为user，密码是程序启动时输出的
    enabled: false

server:
  port: 9080
  session:
    timeout: 600


gwf:
  security:
    browser:
      loginPage: /demo-signIn.html
      loginType: JSON
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
    social:
      qq:
        app-id:
        app-secret:
        providerId: qq
      filterProcessesUrl : /auth
      weixin:
        app-id:
        app-secret:
        providerId: weixin
    code:
      image:
        width: 100  # 宽高可从浏览器获取
        heigth: 100
        length: 4
        url: /user,/user/*
        expireIn: 160
      sms:
        length: 6
        url: /user,/user/*
        expireIn: 160



